/* The `.js` extensions are deliberate: this file is also compiled by the
   `vite.config` TypeScript project, which uses `nodenext` resolution and requires
   them. The application's project resolves them just the same. */
import { SECTIONS } from './sections.js'
import { toSlug } from './slug.js'

/*
The routes the build has to materialise as folders.

The console is served as static files: `UseDefaultFiles()` maps `/zones/` to
`/zones/index.html` and redirects `/zones` with a 301, so that file merely existing
is enough for `dns.example.net/settings/logging/` to work and survive an F5. It is
the same technique any static site generator uses to publish a site without
configuring the server.

It lives in `src/` and not in `vite.config` because the list comes from `SECTIONS`:
if a new sub-section appears tomorrow, its folder is generated by itself.
*/

/*
The routes that no longer have a section of their own: `/allowed/` and `/blocked/`
became the Rules tab of Blocking (CONVENTIONS.md, "Deliberate deviations from
upstream behaviour", item 2). Their
folders are still emitted so a bookmark keeps working; `route.ts` translates them
before reading the route.
*/
export const LEGACY_ROUTES: Record<string, { section: string; sub: string; rule: 'allowed' | 'blocked' }> = {
  allowed: { section: 'blocking', sub: 'Rules', rule: 'allowed' },
  blocked: { section: 'blocking', sub: 'Rules', rule: 'blocked' },
}

export const STATIC_ROUTES: string[] = [
  ...SECTIONS.flatMap((s) => [s.id, ...(s.subs ?? []).map((t) => `${s.id}/${toSlug(t)}`)]),
  ...Object.keys(LEGACY_ROUTES),
]
